<?php return [
    'version' => '0.1.0',
    'default_profile' => 'html',
    'default_theme_mode' => 'auto',
    'default_theme' => 'evo-light',
    'themes' => [
        'light' => ['label' => 'Light', 'theme' => 'evo-light'],
        'dark' => ['label' => 'Dark', 'theme' => 'evo-dark'],
    ],
    'profiles' => [
        'html' => [
            'label' => 'HTML',
            'language' => 'html',
            'extensions' => ['basicSetup', 'modxOverlay', 'fold', 'search', 'emmet'],
            'options' => [
                'lineWrapping' => true,
                'indentUnit' => 4,
                'tabSize' => 4,
                'matchBrackets' => true,
                'activeLine' => true,
            ],
        ],
        'css' => [
            'label' => 'CSS',
            'language' => 'css',
            'extensions' => ['basicSetup', 'fold', 'search', 'emmet'],
            'options' => ['lineWrapping' => true],
        ],
        'js' => [
            'label' => 'JavaScript',
            'language' => 'javascript',
            'extensions' => ['basicSetup', 'fold', 'search'],
        ],
        'php' => [
            'label' => 'PHP',
            'language' => 'php',
            'extensions' => ['basicSetup', 'modxOverlay', 'fold', 'search'],
        ],
        'json' => [
            'label' => 'JSON',
            'language' => 'json',
            'extensions' => ['basicSetup', 'lint', 'search'],
        ],
        'sql' => [
            'label' => 'SQL',
            'language' => 'sql',
            'extensions' => ['basicSetup', 'search'],
        ],
        'plain' => [
            'label' => 'Plain Text',
            'language' => 'plain',
            'extensions' => ['basicSetup'],
        ],
    ],
    'contexts' => [
        'resource' => 'html',
        'template' => 'html',
        'chunk' => 'html',
        'snippet' => 'php',
        'plugin' => 'php',
        'module' => 'php',
        'tv' => 'html',
    ],
    'editor' => [
        'font_size' => 14,
        'line_height' => 1.3,
        'line_wrapping' => true,
        'indent_with_tabs' => true,
        'history' => [
            'persist' => false,
            'max_items' => 200,
            'max_kb' => 256,
            'debounce_ms' => 1250,
        ],
        'state' => [
            'persist_fullscreen' => true,
            'persist_cursor' => true,
            'persist_scroll' => true,
            'persist_snapshot' => false,
        ],
        'gutters' => [
            'markers' => true,
            'fold' => true,
        ],
        'keymap' => [
            'save' => 'Mod-s',
            'save_continue' => 'Mod-e',
            'save_new' => 'Mod-b',
            'save_quit' => 'Mod-q',
        ],
    ],
    'extensions' => [
        'search' => ['enabled' => true],
        'emmet' => ['enabled' => true],
        'lint' => ['enabled' => false],
    ],
    'emmet_snippets' => [
        'summary' => '[[summary? &text=`[*content*]` &len=`200`]]',
        '!summary' => '[!summary? &text=`[*content*]` &len=`200`!]',
        'phpthumb' => '[[phpthumb? &input=`[+image+]` &options=`w=150,h=76,far=C,bg=FFFFFF`]]',
        '!phpthumb' => '[!phpthumb? &input=`[+image+]` &options=`w=150,h=76,far=C,bg=FFFFFF`!]',
        'thumb' => '[[phpthumb? &input=`[+image+]` &options=`w=150,h=76,far=C,bg=FFFFFF`]]',
        '!thumb' => '[!phpthumb? &input=`[+image+]` &options=`w=150,h=76,far=C,bg=FFFFFF`!]',
        'EvoGallery' => '[[EvoGallery? &docId=`[*id*]` &show=`9` &itemTpl=`` &paginate=`1` &paginateNextText=`Вперед` &paginatePreviousText=`Назад`]]',
        '!EvoGallery' => '[!EvoGallery? &docId=`[*id*]` &show=`9` &itemTpl=`` &paginate=`1` &paginateNextText=`Вперед` &paginatePreviousText=`Назад`!]',
        'Ditto' => '[[Ditto? &parents=`` &tpl=`` &orderBy=`pub_date DESC` &paginate=`0` &display=`all` &dateFormat=`%d.%m.%Y` &dateSource=`pub_date`]]',
        '!Ditto' => '[!Ditto? &parents=`` &tpl=`` &orderBy=`pub_date DESC` &paginate=`0` &display=`all` &dateFormat=`%d.%m.%Y` &dateSource=`pub_date`!]',
        'Breadcrumbs' => '[[Breadcrumbs? &templateSet=`defaultString` &showHomeCrumb=`1` &showCrumbsAsLinks=`1`]]',
        '!Breadcrumbs' => '[!Breadcrumbs? &templateSet=`defaultString` &showHomeCrumb=`1` &showCrumbsAsLinks=`1`!]',
        'Wayfinder' => '[[Wayfinder? &startId=`` &level=`` &rowTpl=`` &outerTpl=`` &outerClass=`` &hereClass=`active`]]',
        '!Wayfinder' => '[!Wayfinder? &startId=`` &level=`` &rowTpl=`` &outerTpl=`` &outerClass=`` &hereClass=`active`!]',
        'eForm' => '[!eForm? &formid=`feedbackForm` &subject=`Сообщение с сайта [(site_name)]` &tpl=`eFeedbackForm` &report=`eFeedbackReport` &gotoid=`[*id*]` &vericode=`1`!]',
        '!eForm' => '[!eForm? &formid=`feedbackForm` &subject=`Сообщение с сайта [(site_name)]` &tpl=`eFeedbackForm` &report=`eFeedbackReport` &gotoid=`[*id*]` &vericode=`1`!]',
        'if' => '[[if? &is=`[*a*]+1:=:2` &then=`@TPL:true` &else=`@TPL:false` &math=`on` &separator=`:`]]',
        '!if' => '[!if? &is=`[*a*]+1:=:2` &then=`@TPL:true` &else=`@TPL:false` &math=`on` &separator=`:`!]',
        'UltimateParent' => '[[UltimateParent? &topLevel=`2`]]',
        '!UltimateParent' => '[!UltimateParent? &id=`45` &top=`6`!]',
        'Shopkeeper' => '[!Shopkeeper? &priceTV=`price` &cartType=`full` &cartTpl=`small_CartTpl` &cartRowTpl=`inner_CartTpl` &orderFormPage=`` &noJQuery=`1` ¤cy=`руб`!]',
        '!Shopkeeper' => '[!Shopkeeper? &orderFormPage=`10`!]',
        'multiTV' => '[[multiTV? &tvName=`` &docid=`[*id*]` &tplConfig=`` &outerTpl=`@CODE:<ul>[+wrapper+]</ul>` &rowTpl=`@CODE:<li>[+event+], [+location+], [+price+]</li>` &display=`all` &offset=`0` &orderBy=``]]',
        '!multiTV' => '[!multiTV? &tvName=`` &docid=`[*id*]` &tplConfig=`` &outerTpl=`@CODE:<ul>[+wrapper+]</ul>` &rowTpl=`@CODE:<li>[+event+], [+location+], [+price+]</li>` &display=`all` &offset=`0` &orderBy=``!]',
        '@multiTV' => '@INCLUDE/assets/tvs/multitv/multitv.customtv.php',
        '@choiceTV' => '@INCLUDE /assets/tvs/choicetv/choicetv.php',
    ],
    'protected_keys' => [
        'selector', 'target', 'language', 'extensions', 'theme', 'theme_mode',
        'history', 'keymap', 'gutters',
    ],
];
